### ISSUE TITLE
Provide example dashboard for Grafana

### ISSUE THREAD

**Issue by sschnabe** [kokuwaio/keycloak-event-metrics#2]
Reuse dashboard from [kokuwa/keycloak](https://github.com/kokuwaio/keycloak/blob/main/src/test/k3s/grafana/files/dashboards/keycloak-monitoring.json) and add documentation in readme

**Comment by JakeTheSnake** [comment]
How's it going with this one? I'd like to help but I really do not have a talent for grafana dashboards..

**Comment by YuriB9** [comment]
+1 Still waiting for cool dashboard...

**Comment by sschnabe** [comment]
There is a dashboard: [kokuwaio/keycloak](https://github.com/kokuwaio/keycloak/blob/main/src/test/k3s/dev/grafana/files/dashboards/keycloak-monitoring.json)

I can polish it and deploye it somewhere. Where would you expect this dashboard? grafana.com? In This repository?

**Comment by JakeTheSnake** [comment]
Isn't this dashboard for the old metrics SPI? I don't have any of those keys (i.e. "keycloak_logins") in my metrics exposed by this plugin. Mine look like this:

`keycloak_event_user_total{client="my-client",error="",realm="my-realm",type="CODE_TO_TOKEN",} 4151.0`

**Comment by sschnabe** [comment]
Oh, i missed your comment. You're right! I've updated the dashboard with [kokuwaio/keycloak!141](https://github.com/kokuwaio/keycloak/pull/141). Please check if you are still interested.

**Comment by sschnabe** [comment]
@JakeTheSnake I've resolved your findings. Thx for your help!
