### ISSUE TITLE
More detailed Metrics

### ISSUE THREAD

**Issue by subhidh** [kokuwaio/keycloak-event-metrics#63]
Can we also get these metrics - 
```
keycloak_failed_login_attempts
keycloak_failed_authentication_attempts
keycloak_failed_authorization_attempts
keycloak_login_success_total
keycloak_login_failure_total
keycloak_authorization_success_total
keycloak_authorization_failure_total
```

**Comment by sschnabe** [comment]
From which event you want to create this metrics?

**Comment by subhidh** [comment]
These are from User events

**Comment by subhidh** [comment]
Hello, can this be done?

**Comment by sschnabe** [comment]
Of course this can be done, just create a pull request. I myself have no time at the moment and i don't know which events are missing.

**Comment by subhidh** [comment]
ok, sure I'll add and raise PR

**Comment by sschnabe** [comment]
@subhidh any updates?

**Comment by sschnabe** [comment]
Closed because no response.
